name: AnuDB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Ensures third_party/nanomq is initialized

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Prepare Build Directory
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run Tests (if applicable)
      run: |
        cd build
        ctest --output-on-failure || echo "No tests found or some tests failed"
